### ISSUE TITLE
upb_proto_library does not respect strip_include_prefix

### ISSUE THREAD

**Issue by bholmes-sc** [protocolbuffers/upb#1040]
When using `strip_include_prefix` in the proto_library() declaration, the upb_proto_library rule will fail.

```
ERROR: /Users/bholmes/Dev/upb/upb/test/BUILD:174:14: in //bazel:upb_proto_library.bzl%upb_proto_library_aspect aspect on proto_library rule //upb/test:test_stripped_prefix_proto:
Traceback (most recent call last):
	File "/Users/bholmes/Snapchat/Dev/upb/bazel/upb_proto_library.bzl", line 320, column 34, in upb_proto_library_aspect_impl
		return _upb_proto_aspect_impl(target, ctx, "upb", UpbWrappedCcInfo, UpbWrappedGeneratedSrcsInfo)
	File "/Users/bholmes/Snapchat/Dev/upb/bazel/upb_proto_library.bzl", line 299, column 32, in _upb_proto_aspect_impl
		files = _compile_upb_protos(ctx, generator, proto_info, proto_info.direct_sources)
	File "/Users/bholmes/Snapchat/Dev/upb/bazel/upb_proto_library.bzl", line 235, column 34, in _compile_upb_protos
		srcs = [_generate_output_file(ctx, name, ext + ".c") for name in proto_sources]
	File "/Users/bholmes/Snapchat/Dev/upb/bazel/upb_proto_library.bzl", line 90, column 39, in _generate_output_file
		real_short_path = paths.relativize(real_short_path, package)
	File "/private/var/tmp/_bazel_bholmes/3427c17ac33700191f21c746618a87c9/external/bazel_skylib/lib/paths.bzl", line 182, column 13, in _relativize
		fail("Path '%s' is not beneath '%s'" % (path, start))
```

The build configuration I have looks like this:
```
proto_library(
    name = "test_stripped_prefix_proto",
    srcs = ["test_stripped_prefix.proto"],
    strip_import_prefix = "",
)

upb_proto_library(
    name = "test_stripped_prefix_upb_proto",
    testonly = 1,
    visibility = ["//:__subpackages__"],
    deps = [":test_stripped_prefix_proto"],
)
```

**Comment by phst** [comment]
One thing that appears to be incorrect (maybe unrelated) is that µpb tries to strip the prefix from the Bazel package instead of the filename. This breaks when using µpb with released protobuf versions; I therefore had to patch it for rules_elisp (https://github.com/phst/rules_elisp/blob/81f934702cf3e6ee2da7cf5b00116cafbb518168/upb.patch#L12-L30).

**Comment by haberman** [comment]
Patches welcome. I saw a change today that looks related, but it's failing CI: https://github.com/protocolbuffers/upb/pull/1042

**Comment by haberman** [comment]
The real solution here will be to use `proto_common.compile()`, once that is available in Bazel. It will handle all of these corner cases properly. But I don't know when it will be available.

**Comment by phst** [comment]
Maybe in the meantime it would be preferable to remove support for strip_import_prefix entirely (i.e. ignore the attribute)?

**Comment by haberman** [comment]
I think that would break existing builds. We currently use upb_proto_library() with rules that use `strip_import_prefix`, for example https://github.com/protocolbuffers/protobuf/blob/883ec1c3ef8be0bae01cf9ad74e1adde977afeec/src/google/protobuf/BUILD.bazel#L18-L84
