### ISSUE TITLE
How to generate .upb.h is not introduced in the test and examples

### ISSUE THREAD

**Issue by coretimes** [protocolbuffers/upb#365]
How to generate .upb.h is not introduced in the test and examples, and the .upb.h,.upb.c file generated by proto is not seen after all compilation is completed.

The examples build generates foo_proto-descriptor-set.proto.bin, how to generate .h and .c

centos7:
root@192 /h/u/e/bazel# bazel build //:foo_upbproto
ERROR: /home/upb/examples/bazel/BUILD:6:14: in @upb//bazel:upb_proto_library.bzl%_upb_proto_library_aspect aspect on proto_library rule //:foo_proto: 
Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/8eaf3d07925217b3c1325b559a253545/external/upb/bazel/upb_proto_library.bzl", line 192, column 32, in _upb_proto_aspect_impl
		files = _compile_upb_protos(ctx, proto_info, proto_info.direct_sources, ctx.attr._ext)
	File "/root/.cache/bazel/_bazel_root/8eaf3d07925217b3c1325b559a253545/external/upb/bazel/upb_proto_library.bzl", line 149, column 34, in _compile_upb_protos
		srcs = [_generate_output_file(ctx, name, ext + ".c") for name in proto_sources]
	File "/root/.cache/bazel/_bazel_root/8eaf3d07925217b3c1325b559a253545/external/upb/bazel/upb_proto_library.bzl", line 45, column 23, in _generate_output_file
		ret = ctx.new_file(ctx.genfiles_dir, output_filename)
Error in new_file: Use ctx.actions.declare_file instead of ctx.new_file. 
Use --incompatible_new_actions_api=false to temporarily disable this check.
ERROR: Analysis of target '//:foo_upbproto' failed; build aborted: Analysis of target '//:foo_proto' failed
INFO: Elapsed time: 0.194s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by haberman** [comment]
The error above (`Error in new_file: Use ctx.actions.declare_file instead of ctx.new_file.`) was fixed in https://github.com/protocolbuffers/upb/pull/177.

The example itself has been removed, but the example you were trying should be working now.
