### ISSUE TITLE
upb is broken with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [protocolbuffers/upb#784]
First reported at https://github.com/bazelbuild/continuous-integration/issues/1439

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2631#01833787-115d-48d9-938c-084b2f36562c

```
5:46:27) ERROR: /var/lib/buildkite-agent/builds/bk-docker-xlpj/bazel-downstream-projects/upb/upb/bindings/lua/BUILD.bazel:96:14: in //upb/bindings/lua:lua_proto_library.bzl%_lua_proto_library_aspect aspect on proto_library rule //upb/bindings/lua:test_proto:
Traceback (most recent call last):
	File "/var/lib/buildkite-agent/builds/bk-docker-xlpj/bazel-downstream-projects/upb/upb/bindings/lua/lua_proto_library.bzl", line 118, column 32, in _lua_proto_library_aspect_impl
		files = _compile_upb_protos(ctx, proto_info, proto_info.direct_sources)
	File "/var/lib/buildkite-agent/builds/bk-docker-xlpj/bazel-downstream-projects/upb/upb/bindings/lua/lua_proto_library.bzl", line 82, column 35, in _compile_upb_protos
		files = [_generate_output_file(ctx, name, "_pb.lua") for name in proto_sources]
	File "/var/lib/buildkite-agent/builds/bk-docker-xlpj/bazel-downstream-projects/upb/upb/bindings/lua/lua_proto_library.bzl", line 69, column 39, in _generate_output_file
		real_short_path = paths.relativize(real_short_path, package)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2056df990a8711c59c264304314251c8/external/bazel_skylib/lib/paths.bzl", line 182, column 13, in _relativize
		fail("Path '%s' is not beneath '%s'" % (path, start))
Error in fail: Path 'upb/bindings/lua/test.proto' is not beneath '/lua'
```

A manual bisect points to https://github.com/bazelbuild/bazel/commit/b33c5352fe59ded9dfcf10668bf104f977092218

@comius I know when you enabled the Starlark proto library, the downstream was green for upb, I guess there are new changes in upb that are broken by the Starlark proto library. Can you advise how to fix upb?

**Comment by Wyverald** [comment]
> the downstream was green for upb, I guess there are new changes in upb that are broken by the Starlark proto library

Downstream was green for upb because upb was stuck on an old commit back then (due to the master->main switch).

**Comment by meteorcloudy** [comment]
Ah, I see, but it stays true that new commits are broken with the Starlark proto library. We could have caught the issue if the master -> main switch was noticed earlier.
