### ISSUE TITLE
Compatibility problem of upb -> field with proto3_optional was not in a oneof (versionpb.etcd_version_msg)

### ISSUE THREAD

**Issue by ChameleonRed** [protocolbuffers/upb#813]
I want to use protobuf 4.x and migration from 4.x is impossible since differences.

I generate code from etcd proto files.
See all: https://github.com/etcd-io/etcd/tree/main/api

This problem is related to this:

https://github.com/etcd-io/etcd/blob/main/api/versionpb/version.proto

```
Traceback (most recent call last):
  File "C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\test\authentication\sync_etcd3_client_authentication_server_localhost.py", line 8, in <module>
    from authentication.grpc import authentication_pb2_grpc, authentication_pb2
  File "C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\src\authentication\__init__.py", line 9, in <module>
    from authentication.etcd3_client_connector import AuthenticationEtcd3ClientConnector
  File "C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\src\authentication\etcd3_client_connector.py", line 21, in <module>
    from etcd3_client.client import EtcdClient
  File "C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\src\etcd3_client\client.py", line 16, in <module>
    from etcd3_client.base_client import BaseEtcdClient
  File "C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\src\etcd3_client\base_client.py", line 8, in <module>
    from etcd3_grpc.grpc.etcd.api.etcdserverpb import rpc_pb2
  File "C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\src\etcd3_grpc\grpc\etcd\api\etcdserverpb\rpc_pb2.py", line 17, in <module>
    from etcd.api.versionpb import version_pb2 as etcd_dot_api_dot_versionpb_dot_version__pb2
  File "C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\src\etcd3_grpc\grpc\etcd\api\versionpb\version_pb2.py", line 18, in <module>
    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n etcd/api/versionpb/version.proto\x12\tversionpb\x1a\x14gogoproto/gogo.proto\x1a google/protobuf/descriptor.proto:>\n\x10\x65tcd_version_msg\x12\x1f.google.protobuf.MessageOptions\x18\xd0\x86\x03 \x01(\t\x88\x01\x01:>\n\x12\x65tcd_version_field\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\t\x88\x01\x01:<\n\x11\x65tcd_version_enum\x12\x1c.google.protobuf.EnumOptions\x18\xd2\x86\x03 \x01(\t\x88\x01\x01:G\n\x17\x65tcd_version_enum_value\x12!.google.protobuf.EnumValueOptions\x18\xd3\x86\x03 \x01(\t\x88\x01\x01\x42\x08\xc8\xe2\x1e\x01\xd0\xe2\x1e\x01\x62\x06proto3')
TypeError: Couldn't build proto file into descriptor pool: field with proto3_optional was not in a oneof (versionpb.etcd_version_msg)
```

This field is generating problem:

```
// Indicates etcd version that introduced the message, used to determine minimal etcd version required to interpret wal that includes this message.
extend google.protobuf.MessageOptions {
  optional string etcd_version_msg = 50000;
}
```

I see nothing special here since it is only optional keyword - why not?

**Comment by ChameleonRed** [comment]
Here is upb code which generates error.


https://github.com/protocolbuffers/upb/blob/1e3deb013df2cefc0049bfc8f89bee9655c172fa/upb/reflection/field_def.c#L656

**Comment by bezmax** [comment]
I actualy have opened another issue about this yesterday:

https://github.com/protocolbuffers/upb/issues/812

**Comment by ChameleonRed** [comment]
> I actualy have opened another issue about this yesterday:
> 
> #812

So it is rather udp problem since wrong encoding proto descriptors.

**Comment by bezmax** [comment]
Yes, it's incorrectly parsing compiled descriptors of optional fields in `extends` clauses.
